name: CI

on:
    push:
        branches: [release]
    pull_request:
        branches: [release]

jobs:
    deploy:
        runs-on: ubuntu-latest
        needs: build
        steps:
            - name: Deploy to my EC2 instance
              uses: easingthemes/ssh-deploy@main
              with:
                  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
                  SOURCE: './'
                  REMOTE_HOST: 'ec2-13-48-56-99.eu-north-1.compute.amazonaws.com'
                  REMOTE_USER: 'ubuntu'
                  TARGET: '/var/www/html/mediumclone-angular/dist/mediumclone_angular'
