name: CI

on:
    push:
        branches: [release]
    pull_request:
        branches: [release]

jobs:
    build:
        # using Ubuntu
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ./
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: '20.x'
            - uses: actions/cache@v3
              with:
                  path: ~/.npm
                  key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
                  restore-keys: |
                      ${{ runner.os }}-node-
            - name: NPM Install
              run: npm install --force --legacy-peer-deps
            - name: NPM Install Angular
              run: npm install -g @angular/cli > /dev/null
            - name: Lint
              run: npm run lint
            - name: Format
              run: npm run format
            - name: NPM build Angular Production
              run: npm run build:prod
            # - name: Test
            #   run: npm run test:ci
            # - name: Test coverage
            #   run: npm run test:ci:cov
            - name: Deploy to my EC2 instance
              uses: easingthemes/ssh-deploy@release
              with:
                  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
                  SOURCE: 'dist/'
                  REMOTE_HOST: 'ec2-13-48-56-99.eu-north-1.compute.amazonaws.com'
                  REMOTE_USER: 'ubuntu'
                  TARGET: '/var/www/html/mediumclone-angular/dist/mediumclone_angular'
